In [1]:
import numpy as np 

from MissingImputer import MissingImputer

In [2]:
X = np.array([
    [3,0, np.nan, np.nan],  # odd: implicit zero
    [2,5, np.nan, np.nan],  # odd: explicit nonzero
    [7,0, 0, np.nan],    # even: average two zeros
    [8,-5, 0, np.nan],   # even: avg zero and neg
    [2,0, 5, np.nan],    # even: avg zero and pos
    [1,4, 5, np.nan],    # even: avg nonzeros
    [-3,-4, -5, np.nan],  # even: avg negatives
    [0,-1, 2, np.nan],   # even: crossing neg and pos
]).transpose()

In [3]:
MissImputer = MissingImputer(ini_fill = True, model_reg = "knn", model_clf = "knn")
MissImputer

In [4]:
X_trans = MissImputer.fit(X, model_params = {'regressor':{'n_neighbors':1}, 'classifier':{}}).transform(X.copy())

[[ 3.  2.  7.  8.  2.  1. -3.  0.]
 [ 0.  5.  0. -5.  0.  4. -4. -1.]
 [ 0.  5.  0.  0.  5.  5. -5.  2.]
 [ 0.  5.  0.  0.  5.  5. -5.  2.]]


In [ ]:
X_trans

In [ ]:
MissImputer = MissingImputer(ini_fill = True, model_reg = "xgboost", model_clf = "xgboost")
MissImputer

In [ ]:
X_trans = MissImputer.fit(X).transform(X.copy())

In [ ]:
print(X_trans)

In [ ]:
MissImputer = MissingImputer(max_iter = 6, ini_fill = True, model_reg = "randomforest", model_clf = "randomforest")
MissImputer

In [ ]:
X_trans = MissImputer.fit(X).transform(X.copy())

In [ ]:
X_trans